MVC_Project/Controllers/CartController.cs
using MVC_Project.Models.VM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Project.Controllers
{
     
    public class CartController : Controller
    {
        Entities1 db = new Entities1();
        // GET: Cart
        public ActionResult Index()
        {
            User user = (User)Session["user"];
            var cart = (from c in db.Carts
                        where c.User_Id == user.U_Id
                        select c);
            List<ProductCart> prodsCart = new List<ProductCart>();
            if (user == null)
                return RedirectToAction("Index","Home"); ;
            foreach (var item in cart)
            {
                var prods = (from p in db.Products
                                where p.Product_Id == item.Product_Id
                                select p).FirstOrDefault();
                var imgUrl= (from p in db.ProductImages
                             where p.Product_Id == item.Product_Id
                             select p.Img_Url).FirstOrDefault();
                ProductCart prod = new ProductCart();
                prod.ImgUrl = imgUrl;
                prod.Prodcut_Id = item.Product_Id;
                prod.Product_Name = prods.Name;
                prod.Quantity = item.Quantity;
                prod.ItemTotalPrice = prods.Price * item.Quantity;
                prod.price = prods.Price;

                prodsCart.Add(prod);
            }
            return View(prodsCart);
        }
      
        public void Add(int id)
        {
            User user = (User)Session["user"];
            var cart = (from c in db.Carts
                        where c.Product_Id == id&&c.User_Id==user.U_Id
                        select c).FirstOrDefault();
            if(cart==null)
            {
                Cart cart1 = new Cart();
                cart1.Product_Id = id;
                cart1.Quantity = 1;
                cart1.User_Id = user.U_Id;
                db.Carts.Add(cart1);
                db.SaveChanges();
            }else
            {
                cart.Quantity++;
                db.SaveChanges();
            }
            //return RedirectToAction("Index");
        }
        public ActionResult AddFromDetails(int id,int quantity)
        {
            User user = (User)Session["user"];
            var cart = (from c in db.Carts
                        where c.Product_Id == id && c.User_Id == user.U_Id
                        select c).FirstOrDefault();
            if (cart == null)
            {
                Cart cart1 = new Cart();
                cart1.Product_Id = id;
                cart1.Quantity = quantity;
                cart1.User_Id = user.U_Id;
                db.Carts.Add(cart1);
                db.SaveChanges();
            }
            else
            {
                cart.Quantity+= quantity;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public ActionResult Remove(int id)
        {
            var cart = (from c in db.Carts
                        where c.Product_Id == id
                        select c).FirstOrDefault();
            db.Carts.Remove(cart);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MVC_Project/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC_Project;

namespace MVC_Project.Controllers
{
    public class CategoriesController : Controller
    {
        private Entities1 db = new Entities1();

        // GET: Categories
        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }

        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create([Bind(Include = "Cat_Id,Name,Description")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Edit([Bind(Include = "Cat_Id,Name,Description")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
     
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC_Project/Controllers/OrderController.cs
using MVC_Project.Models.VM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Project.Controllers
{
    public class OrderController : Controller
    {
        Entities1 context = new Entities1();
        // GET: Order
        public ActionResult Index()
        {
            User user = (User)Session["user"];
            int userId = user.U_Id;
            Entities1 context = new Entities1();
            var query =
                (from o in context.Orders
                 where o.User_Id == userId
                 select o).ToList();



            return View(query);
        }
        public ActionResult Add()
        {
            User user = (User)Session["user"];
            int userId = user.U_Id;

            var query =
                (from o in context.Carts
                 where o.User_Id == userId
                 select new { o.Product_Id, o.Product.Price, o.Quantity, o.Product }).ToList();
            decimal totalPrice = 0;
            if (query.Count > 0)
            {
                foreach (var item in query)
                {
                    totalPrice += item.Price * item.Quantity;
                }
            }
            //  add new order
            Order newOrder = new Order();
            newOrder.User_Id = userId;
            newOrder.Total_Price = totalPrice;
            newOrder.Sales_Date = DateTime.Now;
            context.Orders.Add(newOrder);
            context.SaveChanges();

            var oId =
                (from o in context.Orders
                 select o.O_Id).Max();
            
            //  add order details
            foreach (var item in query)
            {
                order_details odetails = new order_details();
                odetails.O_Id = oId;
                odetails.p_id = item.Product_Id;
                odetails.Quantity = item.Quantity;
                odetails.Price = (int)item.Product.Price;

                context.order_details.Add(odetails);
                updateQuantity(item.Product_Id, item.Quantity);
            }
            context.SaveChanges();
            return RedirectToAction("Index");
            //return View();
        }
        public ActionResult Details(int id)
        {
            Entities1 context = new Entities1();
            var query =
                (from d in context.order_details
                 where d.O_Id == id
                 select d).ToList();

            
            List<ProductCart> products = new List<ProductCart>();
            foreach (var item in query)
            {
                ProductCart product = new ProductCart();
                product.ImgUrl = (from i in context.ProductImages where i.Product_Id == item.p_id select i.Img_Url).FirstOrDefault();
                product.Product_Name = item.Product.Name;
                product.price = item.Product.Price;
                product.Quantity = item.Quantity;
                product.ItemTotalPrice = item.Order.Total_Price;
                products.Add(product);
            }


            return View(products);
        }

        public void updateQuantity(int pId, int qty)
        {
            Entities1 context = new Entities1();
            var query =
                (from p in context.Products
                 where p.Product_Id == pId
                 select new { p, p.Quantity }).FirstOrDefault();

            int newQty = query.Quantity - qty;
            query.p.Quantity = newQty;
            context.SaveChanges();


        }

    }
}

MVC_Project/Controllers/ProductCatController.cs
using MVC_Project.Models.VM;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Project.Controllers
{
    public class ProductCatController : Controller
    {
        Entities1 db = new Entities1();
        // GET: ProductCat
        public ActionResult MobileAndTabs(string searchString, string currentFilter, int? page)
        {
            List<ProductVM> prodList = new List<ProductVM>();
            prodList = cateogryList(page, searchString,currentFilter,4);
            int pageSize = 9;
            int pageNumber = (page ?? 1);
            return View(prodList.ToPagedList(pageNumber, pageSize));
           
        }
        public ActionResult Computers(string searchString, string currentFilter, int? page)
        {
            List<ProductVM> prodList = new List<ProductVM>();
            prodList = cateogryList(page, searchString, currentFilter, 6);
            int pageSize = 9;
            int pageNumber = (page ?? 1);
            return View(prodList.ToPagedList(pageNumber, pageSize));

        }
        List<ProductVM> cateogryList(int?page,string searchString,string currentFilter,int id)
        {
            List<ProductVM> prodList = new List<ProductVM>();
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var prods = (from p in db.Products
                         where p.Cat_Id == id
                         select p);
            if (!String.IsNullOrEmpty(searchString))
            {
                prods = prods.Where(s => s.Name.Contains(searchString));
            }
            foreach (var item in prods)
            {
                var prodImg = (from i in db.ProductImages
                               where i.Product_Id == item.Product_Id
                               select i.Img_Url).FirstOrDefault();
                ProductVM prod = new ProductVM();
                prod.Product_Id = item.Product_Id;
                prod.Name = item.Name;
                prod.Price = item.Price;
                prod.Description = item.Description;
                prod.Brand = item.Brand;
                prod.ImgUrl = prodImg;
                prod.Quantity = item.Quantity;
                prod.Rate = 0;
                prodList.Add(prod);
            }
            return prodList;
        }

    }
}

MVC_Project/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC_Project;

namespace MVC_Project.Controllers
{
    public class ProductsController : Controller
    {
        private Entities1 db = new Entities1();

        // GET: Products
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.Category);
            return View(products.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.Cat_Id = new SelectList(db.Categories, "Cat_Id", "Name");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
      
        public ActionResult Create([Bind(Include = "Product_Id,Name,Price,Description,Quantity,Brand,Cat_Id")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Cat_Id = new SelectList(db.Categories, "Cat_Id", "Name", product.Cat_Id);
            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.Cat_Id = new SelectList(db.Categories, "Cat_Id", "Name", product.Cat_Id);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        
        public ActionResult Edit([Bind(Include = "Product_Id,Name,Price,Description,Quantity,Brand,Cat_Id")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Cat_Id = new SelectList(db.Categories, "Cat_Id", "Name", product.Cat_Id);
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
      
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC_Project/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVC_Project/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVC_Project/Views/Home/Index.cshtml
@model PagedList.IPagedList<MVC_Project.Models.VM.ProductVM>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Home Page";
}
@using (Html.BeginForm())
{
    <p style="margin-top:20px">
        Find by name: @Html.TextBox("SearchString")
        <input class="btn" type="submit" value="Search" />
    </p>
}

<div class="container">
    <div class="row">

        @foreach (var item in Model)
        {
            <div class="col-sm-3">
                <div class="col-item">
                    <div class="photo">
                        <img src="@item.ImgUrl" class="img-responsive" alt="a" />
                    </div>
                    <div class="info">
                        <div class="row">
                            <div class="price col-md-6">
                                <h5>
                                    @item.Name
                                </h5>
                                <h5 class="price-text-color">
                                    $@item.Price
                                </h5>
                            </div>
                            <div class="rating hidden-sm col-md-6">
                                @if (item.Rate == 0)
                                {

                                }
                                @if (item.Rate == 1)
                                {
                                    <i class="price-text-color fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                }
                                @if (item.Rate == 2)
                                {
                                    <i class="price-text-color fa fa-star"></i>
                                    <i class="price-text-color fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                }
                                @if (item.Rate == 3)
                                {
                                    <i class="price-text-color fa fa-star"></i>
                                    <i class="price-text-color fa fa-star"></i>
                                    <i class="price-text-color fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                }
                                @if (item.Rate == 4)
                                {
                                    <i class="price-text-color fa fa-star"></i>
                                    <i class="price-text-color fa fa-star"></i>
                                    <i class="price-text-color fa fa-star"></i>
                                    <i class="price-text-color fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                }
                                @if (item.Rate == 5)
                                {
                                    <i class="price-text-color fa fa-star"></i>
                                    <i class="price-text-color fa fa-star"></i>
                                    <i class="price-text-color fa fa-star"></i>
                                    <i class="price-text-color fa fa-star"></i>
                                    <i class="price-text-color fa fa-star"></i>
                                }
                            </div>
                        </div>
                        <div class="separator clear-left">
                            <p class="btn-add">
                                <i class="fa fa-shopping-cart"></i><br>@Html.ActionLink("Add to cart", "Add", "Cart", new { id = item.Product_Id }, null)
                            </p>
                            <p class="btn-details">
                                <i class="fa fa-list"></i><a class="hidden-sm">@Html.ActionLink("More details", "PrductDetails", "Home",item,null)</a>
                            </p>
                        </div>
                        <div class="clearfix">
                        </div>
                    </div>
                </div>
            </div>
        }

    </div>
</div>


@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page,currentFilter = ViewBag.CurrentFilter }))

MVC_Project/Views/Home/NavAnonymousUser.cshtml
@{

    ViewBag.Title = "NavAnonymousUser";
}

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Shop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>@Html.ActionLink("Register", "Register", "Account")</li>
                <li>@Html.ActionLink("Login", "login", "Account")</li>
            </ul>
        </div>
    </div>
</div>

MVC_Project/Views/Home/NavAuthorizedUser.cshtml
@{
    ViewBag.Title = "NavAuthorizedUser";
}
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Shop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Products<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Product", "Index", "Products")</li>
                        <li>@Html.ActionLink("Images", "Index", "ProductImages")</li>
                    </ul>
                </li>
                <li>@Html.ActionLink("Category", "Index", "Categories")</li>
                <li>@Html.ActionLink("Orders", "Orders", "Home")</li>
            </ul>
            <ul class="nav navbar-nav navbar-right">

                <li>@Html.ActionLink("Logout", "Logoff", "Account")</li>
            </ul>
        </div>
    </div>
</div>

MVC_Project/Views/Home/Orders.cshtml
@model List<MVC_Project.Models.VM.OrderVM>
@{
    ViewBag.Title = "Orders";
}

<div class="container">
    <table class="table">
        <thead>
            <tr>

                <th>User Name</th>
                <th>Total Price</th>
                <th>Oder Date</th>
            </tr>
        </thead>
        @foreach (var item in Model)
        {
            <tbody>

                <tr>
                    <td>@item.Username</td>
                    <td>@item.TotalPrice</td>
                    <td>@item.OrderDate</td>
                    <td><button class="btn btn-primary" type="button" onclick="location.href='@Url.Action("Details", "Order", new { id = item.OrderID })'">Details</button></td>
                </tr>
            </tbody>
        }
    </table>
</div>

MVC_Project/Views/Home/PrductDetails.cshtml
@model MVC_Project.Models.VM.ProductVM
@{
    ViewBag.Title = "PrductDetails";
}

<div class="container" style="margin-top:25px">
    <div class="row" style="height:350px;">
        @*<div class="col-md-1" style="height:inherit;background-color:;">
            <div class="" style="height:20%; border:1px grey solid;margin-bottom:5%;"></div>
            <div class="" style="height:20%; border:1px grey solid;margin-bottom:5%;"></div>
        </div>*@

        <div class="col-md-4" style="height:inherit;border:1px grey solid;">
            <img src="@Model.ImgUrl" style="margin:0 auto" />

        </div>

        <div class="col-md-4" style="margin-top:auto;text-align:center;height:inherit;">
            <table style="text-align:left;">
                <tr>
                    <td style="font-size:large;">Name :</td>
                    <td style="color:blue;">@Html.DisplayFor(model => model.Name)</td>
                </tr>
                <tr>
                    <td style="font-size:large;">Price :</td>
                    <td style="color:blue;">@Html.DisplayFor(model => model.Price)</td>
                </tr>
                <tr>
                    <td style="font-size:large;">Description :</td>
                    <td style="color:blue;">@Html.DisplayFor(model => model.Description)</td>
                </tr>
                <tr>
                    <td style="font-size:large;">Quantity :</td>
                    <td style="color:blue;">@Html.DisplayFor(model => model.Quantity)</td>
                </tr>
                <tr>
                    <td style="font-size:large;">Brand :</td>
                    <td style="color:blue;">@Html.DisplayFor(model => model.Brand)</td>
                </tr>
               
            </table>

        </div>

        <div class="col-md-4" style="border:1px grey solid;height:inherit;">
            <div class="" style="height:20%;">
                <h3 style="color:blue;">Buy Now</h3>
            </div>
            @using (Html.BeginForm("AddToCart", "Home", FormMethod.Post))
            {
              <input type="hidden" name="Product_ID" value="@Model.Product_Id" />
                <div class="form-group">
                    <text>Availability : <span>on the stock</span></text><br />
                    <h3 style="color:blue; ">@Model.Price</h3><br />
                    @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control", min=1 ,max = Model.Quantity } })
                        @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br />
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Add to Cart" class="btn btn-primary" />
                    </div>
                </div>
            }
        </div>
    </div>
</div>
<hr />

MVC_Project/Views/Home/UserPView.cshtml
@{
    ViewBag.Title = "UserPView";
}
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Shop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Mobiles and Tablets", "MobileAndTabs", "ProductCat")</li>
                <li>@Html.ActionLink("Computers", "Computers", "ProductCat")</li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>@Html.ActionLink("Orders", "Index", "Order")</li>

                <li>@Html.ActionLink(" ", "Index", "Cart",null, new { @class = "glyphicon glyphicon-shopping-cart" })</li>
                <li>@Html.ActionLink("Logout", "Logoff", "Account")</li>
            </ul>
        </div>
    </div>
</div>